### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by wyudong** [citycide/tablemark-cli#1] opened 2017-04-12 08:38 UTC
I run `$ tablemark` on Mac OSX and get the following error:

```
env: node\r: No such file or directory
```

It should be related to different line endings between Windows and Unix. Can you fix that?

Thank you

**Comment by haltcase** [comment] 2017-06-27 00:10
I never saw this issue pop up, sorry to miss it like that. I'll look into this.

So, this is just from running the `tablemark` command alone? Have you installed it globally with `npm i -g tablemark-cli`?

**Comment by haltcase** [comment] 2017-07-08 03:43
@wyudong I don't have a macOS system to test this out but it works fine on Linux ( bash & zsh ) and Windows. If you're able to give more info / a reproducible case feel free to reopen.

**Comment by haltcase** [comment] 2017-07-08 06:59
@wyudong still wasn't able to repro it, but it might be fixed now in `tablemark-cli@1.0.0`. Thanks for reporting!

**Comment by mowies** [comment] 2021-12-20 12:06
I ran into this issue again today with the current version of the CLI on MacOS Big Sur 11.6
After changing the line endings manually to LF instead of CR, it worked fine for me.

**Comment by mowies** [comment] 2021-12-20 12:33
I forked this repo and implemented a small GH actions test pipeline that reproduces the issue. You can find the failing pipeline run here: https://github.com/mowies/tablemark-cli/actions/runs/1602033359

**Comment by haltcase** [comment] 2021-12-30 23:10
Edit: You know, I only just recently rewrote this in TypeScript (and apparently already forgot that it wasn't always that way), so that doesn't have anything to do with it. Regardless, past releases must have used CRLF somehow and this should be resolved soon.

~I think I figured out the cause of this.~ TypeScript uses a platform-specific default for line endings in emitted files (see https://www.typescriptlang.org/tsconfig/#newLine). Since my release builds have been created on Windows, the line endings of the `bin` script (`./dist/cli.js`) were CRLF. Configuring TS to use LF instead should fix this, and the upcoming v3 release will include that change.

Also, npm apparently normalizes line endings when you execute a bin script with it. From what I can tell Yarn doesn't do that which is why the issue appears when using it.

https://github.com/yarnpkg/yarn/issues/8106

**Comment by haltcase** [comment] 2022-04-30 04:17
Apologies for the delay, but this should be resolved with the release of [v3.0.0](https://github.com/haltcase/tablemark-cli/releases/tag/v3.0.0) and covered by new test cases.

**Closed as completed by haltcase** 2022-04-30 04:17 UTC
Labels: bug
